repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: pnpm exec prettier --write --ignore-unknown
        language: system
        files: \.(js|mjs|cjs|ts|tsx|jsx|json|jsonc|css|astro|md)$
        pass_filenames: true
