name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install dependencies
        run: nix develop --command pnpm install --frozen-lockfile

      - name: Lint
        run: nix develop --command pnpm lint

      - name: Test
        run: nix develop --command pnpm test
