// Mock for Astro's `astro:env/client` virtual module under Vitest.
// The real module is generated by the Astro Vite plugin at build/dev time and
// is unavailable in the plain Vite environment Vitest runs in.
export const PUBLIC_R2_URL = 'https://r2.example.com';
